package com.westflow.processruntime.api.response;

import java.time.OffsetDateTime;

// 执行明细用于系统页展示每条任务最终迁移到了哪里。
// 单个离职转办执行明细。
public record HandoverExecutionTaskItemResponse(
        // 源任务标识
        String sourceTaskId,
        // 目标任务标识
        String targetTaskId,
        // 流程实例标识
        String instanceId,
        // 流程定义标识
        String processDefinitionId,
        // 流程键
        String processKey,
        // 流程名称
        String processName,
        // 业务主键
        String businessKey,
        // 业务类型
        String businessType,
        // 业务标题
        String businessTitle,
        // 单据编号
        String billNo,
        // 当前节点标识
        String currentNodeId,
        // 当前节点名称
        String currentNodeName,
        // 目标用户标识
        String targetUserId,
        // 状态
        String status,
        // 处理人用户标识
        String assigneeUserId,
        // 操作人用户标识
        String operatorUserId,
        // 备注
        String comment,
        // 执行时间
        OffsetDateTime executedAt,
        // 是否可转办
        boolean canTransfer,
        // 说明。
        String reason
) {
}
