/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedWorkflowDesignerRouteImport } from './routes/_authenticated/workflow/designer'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedWorkflowDefinitionsListRouteImport } from './routes/_authenticated/workflow/definitions/list'
import { Route as AuthenticatedWorkbenchTodosListRouteImport } from './routes/_authenticated/workbench/todos/list'
import { Route as AuthenticatedSystemUsersListRouteImport } from './routes/_authenticated/system/users/list'
import { Route as AuthenticatedSystemUsersCreateRouteImport } from './routes/_authenticated/system/users/create'
import { Route as AuthenticatedSystemRolesListRouteImport } from './routes/_authenticated/system/roles/list'
import { Route as AuthenticatedSystemPostsListRouteImport } from './routes/_authenticated/system/posts/list'
import { Route as AuthenticatedSystemPostsCreateRouteImport } from './routes/_authenticated/system/posts/create'
import { Route as AuthenticatedSystemDepartmentsListRouteImport } from './routes/_authenticated/system/departments/list'
import { Route as AuthenticatedSystemDepartmentsCreateRouteImport } from './routes/_authenticated/system/departments/create'
import { Route as AuthenticatedSystemCompaniesListRouteImport } from './routes/_authenticated/system/companies/list'
import { Route as AuthenticatedSystemCompaniesCreateRouteImport } from './routes/_authenticated/system/companies/create'
import { Route as AuthenticatedSystemUsersUserIdIndexRouteImport } from './routes/_authenticated/system/users/$userId/index'
import { Route as AuthenticatedSystemPostsPostIdIndexRouteImport } from './routes/_authenticated/system/posts/$postId/index'
import { Route as AuthenticatedSystemDepartmentsDepartmentIdIndexRouteImport } from './routes/_authenticated/system/departments/$departmentId/index'
import { Route as AuthenticatedSystemCompaniesCompanyIdIndexRouteImport } from './routes/_authenticated/system/companies/$companyId/index'
import { Route as AuthenticatedSystemUsersUserIdEditRouteImport } from './routes/_authenticated/system/users/$userId/edit'
import { Route as AuthenticatedSystemPostsPostIdEditRouteImport } from './routes/_authenticated/system/posts/$postId/edit'
import { Route as AuthenticatedSystemDepartmentsDepartmentIdEditRouteImport } from './routes/_authenticated/system/departments/$departmentId/edit'
import { Route as AuthenticatedSystemCompaniesCompanyIdEditRouteImport } from './routes/_authenticated/system/companies/$companyId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowDesignerRoute =
  AuthenticatedWorkflowDesignerRouteImport.update({
    id: '/workflow/designer',
    path: '/workflow/designer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowDefinitionsListRoute =
  AuthenticatedWorkflowDefinitionsListRouteImport.update({
    id: '/workflow/definitions/list',
    path: '/workflow/definitions/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkbenchTodosListRoute =
  AuthenticatedWorkbenchTodosListRouteImport.update({
    id: '/workbench/todos/list',
    path: '/workbench/todos/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersListRoute =
  AuthenticatedSystemUsersListRouteImport.update({
    id: '/system/users/list',
    path: '/system/users/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersCreateRoute =
  AuthenticatedSystemUsersCreateRouteImport.update({
    id: '/system/users/create',
    path: '/system/users/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemRolesListRoute =
  AuthenticatedSystemRolesListRouteImport.update({
    id: '/system/roles/list',
    path: '/system/roles/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemPostsListRoute =
  AuthenticatedSystemPostsListRouteImport.update({
    id: '/system/posts/list',
    path: '/system/posts/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemPostsCreateRoute =
  AuthenticatedSystemPostsCreateRouteImport.update({
    id: '/system/posts/create',
    path: '/system/posts/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDepartmentsListRoute =
  AuthenticatedSystemDepartmentsListRouteImport.update({
    id: '/system/departments/list',
    path: '/system/departments/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDepartmentsCreateRoute =
  AuthenticatedSystemDepartmentsCreateRouteImport.update({
    id: '/system/departments/create',
    path: '/system/departments/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemCompaniesListRoute =
  AuthenticatedSystemCompaniesListRouteImport.update({
    id: '/system/companies/list',
    path: '/system/companies/list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemCompaniesCreateRoute =
  AuthenticatedSystemCompaniesCreateRouteImport.update({
    id: '/system/companies/create',
    path: '/system/companies/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersUserIdIndexRoute =
  AuthenticatedSystemUsersUserIdIndexRouteImport.update({
    id: '/system/users/$userId/',
    path: '/system/users/$userId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemPostsPostIdIndexRoute =
  AuthenticatedSystemPostsPostIdIndexRouteImport.update({
    id: '/system/posts/$postId/',
    path: '/system/posts/$postId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDepartmentsDepartmentIdIndexRoute =
  AuthenticatedSystemDepartmentsDepartmentIdIndexRouteImport.update({
    id: '/system/departments/$departmentId/',
    path: '/system/departments/$departmentId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemCompaniesCompanyIdIndexRoute =
  AuthenticatedSystemCompaniesCompanyIdIndexRouteImport.update({
    id: '/system/companies/$companyId/',
    path: '/system/companies/$companyId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUsersUserIdEditRoute =
  AuthenticatedSystemUsersUserIdEditRouteImport.update({
    id: '/system/users/$userId/edit',
    path: '/system/users/$userId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemPostsPostIdEditRoute =
  AuthenticatedSystemPostsPostIdEditRouteImport.update({
    id: '/system/posts/$postId/edit',
    path: '/system/posts/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDepartmentsDepartmentIdEditRoute =
  AuthenticatedSystemDepartmentsDepartmentIdEditRouteImport.update({
    id: '/system/departments/$departmentId/edit',
    path: '/system/departments/$departmentId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemCompaniesCompanyIdEditRoute =
  AuthenticatedSystemCompaniesCompanyIdEditRouteImport.update({
    id: '/system/companies/$companyId/edit',
    path: '/system/companies/$companyId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/workflow/designer': typeof AuthenticatedWorkflowDesignerRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/system/companies/create': typeof AuthenticatedSystemCompaniesCreateRoute
  '/system/companies/list': typeof AuthenticatedSystemCompaniesListRoute
  '/system/departments/create': typeof AuthenticatedSystemDepartmentsCreateRoute
  '/system/departments/list': typeof AuthenticatedSystemDepartmentsListRoute
  '/system/posts/create': typeof AuthenticatedSystemPostsCreateRoute
  '/system/posts/list': typeof AuthenticatedSystemPostsListRoute
  '/system/roles/list': typeof AuthenticatedSystemRolesListRoute
  '/system/users/create': typeof AuthenticatedSystemUsersCreateRoute
  '/system/users/list': typeof AuthenticatedSystemUsersListRoute
  '/workbench/todos/list': typeof AuthenticatedWorkbenchTodosListRoute
  '/workflow/definitions/list': typeof AuthenticatedWorkflowDefinitionsListRoute
  '/system/companies/$companyId/edit': typeof AuthenticatedSystemCompaniesCompanyIdEditRoute
  '/system/departments/$departmentId/edit': typeof AuthenticatedSystemDepartmentsDepartmentIdEditRoute
  '/system/posts/$postId/edit': typeof AuthenticatedSystemPostsPostIdEditRoute
  '/system/users/$userId/edit': typeof AuthenticatedSystemUsersUserIdEditRoute
  '/system/companies/$companyId': typeof AuthenticatedSystemCompaniesCompanyIdIndexRoute
  '/system/departments/$departmentId': typeof AuthenticatedSystemDepartmentsDepartmentIdIndexRoute
  '/system/posts/$postId': typeof AuthenticatedSystemPostsPostIdIndexRoute
  '/system/users/$userId': typeof AuthenticatedSystemUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/workflow/designer': typeof AuthenticatedWorkflowDesignerRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/system/companies/create': typeof AuthenticatedSystemCompaniesCreateRoute
  '/system/companies/list': typeof AuthenticatedSystemCompaniesListRoute
  '/system/departments/create': typeof AuthenticatedSystemDepartmentsCreateRoute
  '/system/departments/list': typeof AuthenticatedSystemDepartmentsListRoute
  '/system/posts/create': typeof AuthenticatedSystemPostsCreateRoute
  '/system/posts/list': typeof AuthenticatedSystemPostsListRoute
  '/system/roles/list': typeof AuthenticatedSystemRolesListRoute
  '/system/users/create': typeof AuthenticatedSystemUsersCreateRoute
  '/system/users/list': typeof AuthenticatedSystemUsersListRoute
  '/workbench/todos/list': typeof AuthenticatedWorkbenchTodosListRoute
  '/workflow/definitions/list': typeof AuthenticatedWorkflowDefinitionsListRoute
  '/system/companies/$companyId/edit': typeof AuthenticatedSystemCompaniesCompanyIdEditRoute
  '/system/departments/$departmentId/edit': typeof AuthenticatedSystemDepartmentsDepartmentIdEditRoute
  '/system/posts/$postId/edit': typeof AuthenticatedSystemPostsPostIdEditRoute
  '/system/users/$userId/edit': typeof AuthenticatedSystemUsersUserIdEditRoute
  '/system/companies/$companyId': typeof AuthenticatedSystemCompaniesCompanyIdIndexRoute
  '/system/departments/$departmentId': typeof AuthenticatedSystemDepartmentsDepartmentIdIndexRoute
  '/system/posts/$postId': typeof AuthenticatedSystemPostsPostIdIndexRoute
  '/system/users/$userId': typeof AuthenticatedSystemUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/workflow/designer': typeof AuthenticatedWorkflowDesignerRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/system/companies/create': typeof AuthenticatedSystemCompaniesCreateRoute
  '/_authenticated/system/companies/list': typeof AuthenticatedSystemCompaniesListRoute
  '/_authenticated/system/departments/create': typeof AuthenticatedSystemDepartmentsCreateRoute
  '/_authenticated/system/departments/list': typeof AuthenticatedSystemDepartmentsListRoute
  '/_authenticated/system/posts/create': typeof AuthenticatedSystemPostsCreateRoute
  '/_authenticated/system/posts/list': typeof AuthenticatedSystemPostsListRoute
  '/_authenticated/system/roles/list': typeof AuthenticatedSystemRolesListRoute
  '/_authenticated/system/users/create': typeof AuthenticatedSystemUsersCreateRoute
  '/_authenticated/system/users/list': typeof AuthenticatedSystemUsersListRoute
  '/_authenticated/workbench/todos/list': typeof AuthenticatedWorkbenchTodosListRoute
  '/_authenticated/workflow/definitions/list': typeof AuthenticatedWorkflowDefinitionsListRoute
  '/_authenticated/system/companies/$companyId/edit': typeof AuthenticatedSystemCompaniesCompanyIdEditRoute
  '/_authenticated/system/departments/$departmentId/edit': typeof AuthenticatedSystemDepartmentsDepartmentIdEditRoute
  '/_authenticated/system/posts/$postId/edit': typeof AuthenticatedSystemPostsPostIdEditRoute
  '/_authenticated/system/users/$userId/edit': typeof AuthenticatedSystemUsersUserIdEditRoute
  '/_authenticated/system/companies/$companyId/': typeof AuthenticatedSystemCompaniesCompanyIdIndexRoute
  '/_authenticated/system/departments/$departmentId/': typeof AuthenticatedSystemDepartmentsDepartmentIdIndexRoute
  '/_authenticated/system/posts/$postId/': typeof AuthenticatedSystemPostsPostIdIndexRoute
  '/_authenticated/system/users/$userId/': typeof AuthenticatedSystemUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/workflow/designer'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/system/companies/create'
    | '/system/companies/list'
    | '/system/departments/create'
    | '/system/departments/list'
    | '/system/posts/create'
    | '/system/posts/list'
    | '/system/roles/list'
    | '/system/users/create'
    | '/system/users/list'
    | '/workbench/todos/list'
    | '/workflow/definitions/list'
    | '/system/companies/$companyId/edit'
    | '/system/departments/$departmentId/edit'
    | '/system/posts/$postId/edit'
    | '/system/users/$userId/edit'
    | '/system/companies/$companyId'
    | '/system/departments/$departmentId'
    | '/system/posts/$postId'
    | '/system/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/workflow/designer'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/system/companies/create'
    | '/system/companies/list'
    | '/system/departments/create'
    | '/system/departments/list'
    | '/system/posts/create'
    | '/system/posts/list'
    | '/system/roles/list'
    | '/system/users/create'
    | '/system/users/list'
    | '/workbench/todos/list'
    | '/workflow/definitions/list'
    | '/system/companies/$companyId/edit'
    | '/system/departments/$departmentId/edit'
    | '/system/posts/$postId/edit'
    | '/system/users/$userId/edit'
    | '/system/companies/$companyId'
    | '/system/departments/$departmentId'
    | '/system/posts/$postId'
    | '/system/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/workflow/designer'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/system/companies/create'
    | '/_authenticated/system/companies/list'
    | '/_authenticated/system/departments/create'
    | '/_authenticated/system/departments/list'
    | '/_authenticated/system/posts/create'
    | '/_authenticated/system/posts/list'
    | '/_authenticated/system/roles/list'
    | '/_authenticated/system/users/create'
    | '/_authenticated/system/users/list'
    | '/_authenticated/workbench/todos/list'
    | '/_authenticated/workflow/definitions/list'
    | '/_authenticated/system/companies/$companyId/edit'
    | '/_authenticated/system/departments/$departmentId/edit'
    | '/_authenticated/system/posts/$postId/edit'
    | '/_authenticated/system/users/$userId/edit'
    | '/_authenticated/system/companies/$companyId/'
    | '/_authenticated/system/departments/$departmentId/'
    | '/_authenticated/system/posts/$postId/'
    | '/_authenticated/system/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow/designer': {
      id: '/_authenticated/workflow/designer'
      path: '/workflow/designer'
      fullPath: '/workflow/designer'
      preLoaderRoute: typeof AuthenticatedWorkflowDesignerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow/definitions/list': {
      id: '/_authenticated/workflow/definitions/list'
      path: '/workflow/definitions/list'
      fullPath: '/workflow/definitions/list'
      preLoaderRoute: typeof AuthenticatedWorkflowDefinitionsListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workbench/todos/list': {
      id: '/_authenticated/workbench/todos/list'
      path: '/workbench/todos/list'
      fullPath: '/workbench/todos/list'
      preLoaderRoute: typeof AuthenticatedWorkbenchTodosListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/list': {
      id: '/_authenticated/system/users/list'
      path: '/system/users/list'
      fullPath: '/system/users/list'
      preLoaderRoute: typeof AuthenticatedSystemUsersListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/create': {
      id: '/_authenticated/system/users/create'
      path: '/system/users/create'
      fullPath: '/system/users/create'
      preLoaderRoute: typeof AuthenticatedSystemUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/roles/list': {
      id: '/_authenticated/system/roles/list'
      path: '/system/roles/list'
      fullPath: '/system/roles/list'
      preLoaderRoute: typeof AuthenticatedSystemRolesListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/posts/list': {
      id: '/_authenticated/system/posts/list'
      path: '/system/posts/list'
      fullPath: '/system/posts/list'
      preLoaderRoute: typeof AuthenticatedSystemPostsListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/posts/create': {
      id: '/_authenticated/system/posts/create'
      path: '/system/posts/create'
      fullPath: '/system/posts/create'
      preLoaderRoute: typeof AuthenticatedSystemPostsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/departments/list': {
      id: '/_authenticated/system/departments/list'
      path: '/system/departments/list'
      fullPath: '/system/departments/list'
      preLoaderRoute: typeof AuthenticatedSystemDepartmentsListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/departments/create': {
      id: '/_authenticated/system/departments/create'
      path: '/system/departments/create'
      fullPath: '/system/departments/create'
      preLoaderRoute: typeof AuthenticatedSystemDepartmentsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/companies/list': {
      id: '/_authenticated/system/companies/list'
      path: '/system/companies/list'
      fullPath: '/system/companies/list'
      preLoaderRoute: typeof AuthenticatedSystemCompaniesListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/companies/create': {
      id: '/_authenticated/system/companies/create'
      path: '/system/companies/create'
      fullPath: '/system/companies/create'
      preLoaderRoute: typeof AuthenticatedSystemCompaniesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/$userId/': {
      id: '/_authenticated/system/users/$userId/'
      path: '/system/users/$userId'
      fullPath: '/system/users/$userId'
      preLoaderRoute: typeof AuthenticatedSystemUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/posts/$postId/': {
      id: '/_authenticated/system/posts/$postId/'
      path: '/system/posts/$postId'
      fullPath: '/system/posts/$postId'
      preLoaderRoute: typeof AuthenticatedSystemPostsPostIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/departments/$departmentId/': {
      id: '/_authenticated/system/departments/$departmentId/'
      path: '/system/departments/$departmentId'
      fullPath: '/system/departments/$departmentId'
      preLoaderRoute: typeof AuthenticatedSystemDepartmentsDepartmentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/companies/$companyId/': {
      id: '/_authenticated/system/companies/$companyId/'
      path: '/system/companies/$companyId'
      fullPath: '/system/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedSystemCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users/$userId/edit': {
      id: '/_authenticated/system/users/$userId/edit'
      path: '/system/users/$userId/edit'
      fullPath: '/system/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedSystemUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/posts/$postId/edit': {
      id: '/_authenticated/system/posts/$postId/edit'
      path: '/system/posts/$postId/edit'
      fullPath: '/system/posts/$postId/edit'
      preLoaderRoute: typeof AuthenticatedSystemPostsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/departments/$departmentId/edit': {
      id: '/_authenticated/system/departments/$departmentId/edit'
      path: '/system/departments/$departmentId/edit'
      fullPath: '/system/departments/$departmentId/edit'
      preLoaderRoute: typeof AuthenticatedSystemDepartmentsDepartmentIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/companies/$companyId/edit': {
      id: '/_authenticated/system/companies/$companyId/edit'
      path: '/system/companies/$companyId/edit'
      fullPath: '/system/companies/$companyId/edit'
      preLoaderRoute: typeof AuthenticatedSystemCompaniesCompanyIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedWorkflowDesignerRoute: typeof AuthenticatedWorkflowDesignerRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedSystemCompaniesCreateRoute: typeof AuthenticatedSystemCompaniesCreateRoute
  AuthenticatedSystemCompaniesListRoute: typeof AuthenticatedSystemCompaniesListRoute
  AuthenticatedSystemDepartmentsCreateRoute: typeof AuthenticatedSystemDepartmentsCreateRoute
  AuthenticatedSystemDepartmentsListRoute: typeof AuthenticatedSystemDepartmentsListRoute
  AuthenticatedSystemPostsCreateRoute: typeof AuthenticatedSystemPostsCreateRoute
  AuthenticatedSystemPostsListRoute: typeof AuthenticatedSystemPostsListRoute
  AuthenticatedSystemRolesListRoute: typeof AuthenticatedSystemRolesListRoute
  AuthenticatedSystemUsersCreateRoute: typeof AuthenticatedSystemUsersCreateRoute
  AuthenticatedSystemUsersListRoute: typeof AuthenticatedSystemUsersListRoute
  AuthenticatedWorkbenchTodosListRoute: typeof AuthenticatedWorkbenchTodosListRoute
  AuthenticatedWorkflowDefinitionsListRoute: typeof AuthenticatedWorkflowDefinitionsListRoute
  AuthenticatedSystemCompaniesCompanyIdEditRoute: typeof AuthenticatedSystemCompaniesCompanyIdEditRoute
  AuthenticatedSystemDepartmentsDepartmentIdEditRoute: typeof AuthenticatedSystemDepartmentsDepartmentIdEditRoute
  AuthenticatedSystemPostsPostIdEditRoute: typeof AuthenticatedSystemPostsPostIdEditRoute
  AuthenticatedSystemUsersUserIdEditRoute: typeof AuthenticatedSystemUsersUserIdEditRoute
  AuthenticatedSystemCompaniesCompanyIdIndexRoute: typeof AuthenticatedSystemCompaniesCompanyIdIndexRoute
  AuthenticatedSystemDepartmentsDepartmentIdIndexRoute: typeof AuthenticatedSystemDepartmentsDepartmentIdIndexRoute
  AuthenticatedSystemPostsPostIdIndexRoute: typeof AuthenticatedSystemPostsPostIdIndexRoute
  AuthenticatedSystemUsersUserIdIndexRoute: typeof AuthenticatedSystemUsersUserIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedWorkflowDesignerRoute: AuthenticatedWorkflowDesignerRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedSystemCompaniesCreateRoute:
    AuthenticatedSystemCompaniesCreateRoute,
  AuthenticatedSystemCompaniesListRoute: AuthenticatedSystemCompaniesListRoute,
  AuthenticatedSystemDepartmentsCreateRoute:
    AuthenticatedSystemDepartmentsCreateRoute,
  AuthenticatedSystemDepartmentsListRoute:
    AuthenticatedSystemDepartmentsListRoute,
  AuthenticatedSystemPostsCreateRoute: AuthenticatedSystemPostsCreateRoute,
  AuthenticatedSystemPostsListRoute: AuthenticatedSystemPostsListRoute,
  AuthenticatedSystemRolesListRoute: AuthenticatedSystemRolesListRoute,
  AuthenticatedSystemUsersCreateRoute: AuthenticatedSystemUsersCreateRoute,
  AuthenticatedSystemUsersListRoute: AuthenticatedSystemUsersListRoute,
  AuthenticatedWorkbenchTodosListRoute: AuthenticatedWorkbenchTodosListRoute,
  AuthenticatedWorkflowDefinitionsListRoute:
    AuthenticatedWorkflowDefinitionsListRoute,
  AuthenticatedSystemCompaniesCompanyIdEditRoute:
    AuthenticatedSystemCompaniesCompanyIdEditRoute,
  AuthenticatedSystemDepartmentsDepartmentIdEditRoute:
    AuthenticatedSystemDepartmentsDepartmentIdEditRoute,
  AuthenticatedSystemPostsPostIdEditRoute:
    AuthenticatedSystemPostsPostIdEditRoute,
  AuthenticatedSystemUsersUserIdEditRoute:
    AuthenticatedSystemUsersUserIdEditRoute,
  AuthenticatedSystemCompaniesCompanyIdIndexRoute:
    AuthenticatedSystemCompaniesCompanyIdIndexRoute,
  AuthenticatedSystemDepartmentsDepartmentIdIndexRoute:
    AuthenticatedSystemDepartmentsDepartmentIdIndexRoute,
  AuthenticatedSystemPostsPostIdIndexRoute:
    AuthenticatedSystemPostsPostIdIndexRoute,
  AuthenticatedSystemUsersUserIdIndexRoute:
    AuthenticatedSystemUsersUserIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
